### ISSUE TITLE
Roll Release 3.6

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#255] opened 2018-08-10 17:09 UTC
With all the refactoring and modernisation changes, I wonder if it would be worth us rolling a maintenance-style release at some point soon, so that the various changes are 'in the bag' before the redesign work.

Do you have a reasonable idea of the kinds of things more you'd like to get in place as part of this maintenance phase?

For our own use (rather than a listing to go in the release notes), could we also get a list here of the overall changes made? E.g. "Replaced API reading from XML with JSON", "Moved SDK target to XXX", etc.)

**Comment by oliverlockwood** [comment] 2018-08-10 21:02
@mvl22 Good idea.  In answer to your questions:

## Things we should try to get done before releasing:
1.  **Change the new display of the route segment left/right buttons.**  Having got my head around Android Material style a little bit more, I've realised that you're really not meant to have more than one or at most two `FloatingActionButton`s.  I have longer term ideas of more significant improvements to the display of those buttons, but as a short-term fix before getting a release out, I could just make them ordinary `ImageButton`s (likely square).
2.  Remove the `getJourneyXml()` calls - a small piece of tidy up now I'm confident in the relevant migration to JSON.  I'll try to raise this soon.
3.  **Ideally, upgrade `mapsforge`.**  I believe @jezhiggins has made significant progress on this but I don't know if / when he'd be able to get this piece completed.  So depending on that, it may or may not make the cut.  *What do you think, Jez?*
4.  **Ideally, fix #231 - the navigation bar regression.**  However, I don't believe it's worth investing much time in this without the major navigation bar rework, for the reasons described in that issue.  I could spend a few minutes looking at this; but unless the fix is obvious, then I suspect we'll have to live with this regression if we want to cut a release.

## Overall changes - from 3.5 to 3.7
To assess this, since we now squash-merge our PRs, the commit history is pretty readable.  But let me try to sum it up.

### Visible changes
-  Updated SDK versions for compile (19 --> 28), minimum (14 --> 23), and target (19 --> 26).  Some of these changes do in themselves affect the user experience (e.g. how permissions are asked for).
-  Some styling improvements - smalls steps towards Material design
-  Added translations: Deutsch, Español, Français, Italiano, Português, Русский, Türkçe</li>
-  Improved Elevation views: show total elevation gain/loss, improve scale to make the graph more readable.
-  Added phone and opening hours, where available, to POI bubbles
-  Pebble is no longer supported.
-  LiveRide now says "Get ready to arriverai" instead of just "Get ready to" as the final destination is approached.
-  We now show more detail at higher zoom levels, and prevent zooming beyond the max detail level.
-  Fixed a very annoying bug where map location was lost on app reload / orientation change.
-  Fixed a bug where you couldn't remove the final waypoint (so if you misplaced the last one, your only option would have been to cancel the entire route and start again).
-  Increased the max number of waypoints from 12 to 30.
-  Minor improvements to the clarity of some text visible in the app.

### Invisible changes
-  Significant cleanup and simplification of code throughout.
-  Significant upgrades of Gradle, plugins, and almost all libraries (`mapsforge` being the only exception).
-  Improved test coverage a little.
-  Moved to a cleaner internal representation of routes, and consume from the Journey API.
-  CI builds using Travis, with each merged PR pushing out a beta build automatically.
-  Pulled out a lot of hardcoded strings (though some still remain).
-  Started using Kotlin in place of Java.

**Comment by mvl22** [comment] 2018-08-10 21:25
That’s amazing!

**Comment by mvl22** [comment] 2018-08-10 21:48
> how permissions are asked for

Does this mean that the app now asks for contacts permission at the point of needing this, rather than up-front? Great if so.

**Comment by oliverlockwood** [comment] 2018-08-10 21:52
Yes. It's not perfect but it's better.
Are you part of the open beta by the way? You'd be welcome to do some pre release validation :-)

**Comment by oliverlockwood** [comment] 2018-08-15 07:44
@mvl22 Sorry, to clarify regarding permissions - I skimmed over your comment; the Contacts aspect is part of the app I've never used before.  Playing now, I think actually there's a problem there, in as much the latest version of the app doesn't even *ask* for permissions, so there's some unreachable features unless you somehow already have the requisite permissions.  I'll add this to the list of pre-release work 😞

I definitely think it would perhaps you getting onto the beta programme.  It's easy enough to do through a few commands in the Play Store on your phone.

**Comment by mvl22** [comment] 2018-08-15 13:25
I'm on the beta programme, by the way.

**Comment by mvl22** [comment] 2018-08-27 11:13
How are we doing towards this objective?

**Comment by oliverlockwood** [comment] 2018-08-27 13:44
@mvl22 I'm basically just trying to fix the issues that Simon has raised (the bugs, not the feature requests).

**Comment by oliverlockwood** [comment] 2018-09-05 08:43
This is out of the door now.  Closing accordingly.

**Closed by oliverlockwood** 2018-09-05 08:43 UTC
