### ISSUE TITLE
Don't save replans

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#479] opened 2021-07-17 07:48 UTC
Replanned routes should not be saved. It bloats the save list.

**Comment by HilaryN** [comment] 2021-07-17 19:42
Is this a duplicate of #474 ?

**Comment by oliverlockwood** [comment] 2021-07-17 21:15
Whoops, yes it is. I thought of it again, clearly I'm spending more time using the app than coding it at present!

**Closed** 2021-07-17 21:15 UTC
