### ISSUE TITLE
Server: osmTags not returned by POIs API

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#151] opened 2016-09-09 19:29 UTC
As discussed in https://github.com/cyclestreets/android/issues/97#issuecomment-221604069 a few months ago, there is a bug on the server side of the POIs API, whereby `osmTags` are returned as `null`.

This is blocking some app-side development I'd like to do to improve the app.  Is there any chance this could be progressed, please?  I'd happily help dig into this if you can make the code available to me.

**Comment by oliverlockwood** [comment] 2016-11-15 12:53
@mvl22 any update on this bug?  It's been blocking #97 for 6 months now, and having done a bunch of general improvements to the codebase I'd like to start work on the features that originally brought me to this project, if possible :-)

**Comment by mvl22** [comment] 2016-11-15 20:47
I've just tried the API call and its giving me the results fine. Try example 2 at:

https://www.cyclestreets.net/api/v2/pois.locations/

Ensure that `fields=osmTags,...` is being included.

**Comment by oliverlockwood** [comment] 2016-11-17 17:03
@mvl22 the example you give works, but only for `type=cycleparking`.

If you do the same with `type=bikeshops`, it does not work - as per the examples I gave previously.

Another example (the exact same link as your example with only `type` changed:
https://api.cyclestreets.net/v2/pois.locations?type=bikeshops&longitude=0.117950&latitude=52.205303&radius=5&limit=3&fields=id,latitude,longitude,name,osmTags&key=redacted
all the `osmTags` come back as `null`.

In actual fact, it looks like all the data for `type=bikeshops` is massively out of date.  According to both https://overpass-turbo.eu/ (so OpenStreetMap itself) and http://www.benhaywardcycles.co.uk/contact (the shop's website), Ben Hayward Cycles no longer exists on King's Parade, but the CycleStreets API still thinks it's there.

Can you have a look please?

**Comment by mvl22** [comment] 2016-11-17 18:05
OK - thanks, these are useful reproduce cases.

This API comes from a variety of sources and so its generation has become a bit of a mess, because the various queries try to come to a common emulated table format. For the same reason, the API doesn't yet do multiple `type` values as standard queries can't be used. The above cases are useful clear bugs for me to work through and create tests for.

**Comment by oliverlockwood** [comment] 2016-11-17 20:29
Good stuff :+1:

**Comment by oliverlockwood** [comment] 2017-04-13 08:03
@mvl22 any update on this?

I think I originally raised this issue by email in October 2014 so it would be nice to be able to progress at some point 😃

**Comment by mvl22** [comment] 2017-04-16 14:46
This bug is now fixed - it required quite a bit of tracking down. Sorry this took so long to fix. See #97.

**Closed by mvl22** 2017-04-16 14:46 UTC

**Comment by oliverlockwood** [comment] 2017-04-18 07:13
Just closing the loop - I'm happy that this issue appears resolved.  Thanks for getting it done.
