### ISSUE TITLE
Feedback regression

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#157] opened 2016-10-05 21:55 UTC
The "Comment on this route" system currently fails when clicking "Upload!" with "There was a problem sending your comments: null"

Reported in different issue #71.

**Comment by oliverlockwood** [comment] 2016-10-11 09:47
I've started looking at this.  The problem is an `android.os.NetworkOnMainThreadException`, which has no detail message (hence "null").

We obviously need to send feedback in an async fashion.  I'll look into how this can be achieved.

**Comment by oliverlockwood** [comment] 2016-10-11 09:51
The `Route.plotRoute()` does an asynchronous execution and could be used as an alternative.

**Comment by oliverlockwood** [comment] 2016-10-12 10:41
Should be fixed in #162, once that one's been merged.

**Comment by jezhiggins** [comment] 2016-10-12 10:45
> Should be fixed in #162, once that one's been merged.

Top stuff!

**Closed** 2016-10-13 07:46 UTC
