### ISSUE TITLE
Pinch zoom in/out no longer works while in LiveRide

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#384] opened 2020-05-05 16:06 UTC
As reported by a beta user:
>The current beta version seems okay, except that I can't zoom in or out during LiveRide, which would be useful if I am coming up to a complicated junction.

I experienced this myself yesterday (on my Pixel 2, running Android 10, during my daily allocation of exercise), and it's definitely a regression.  May have come in when I upgraded `osmdroid`; I'm not sure.  This should be fairly easy to reproduce on an emulator, and thence fix.

Interestingly you can still zoom _in_ by double tapping, but zooming in or out via pinching is not possible.

**Comment by jezhiggins** [comment] 2020-05-05 17:40
Confirmed on OnePlus 3 running Android 9.

**Comment by oliverlockwood** [comment] 2020-05-05 18:26
A quick use of git-bisect on the emulator proved this - and also #385 - to have been introduced by the merge of PR #374.

**Comment by oliverlockwood** [comment] 2020-05-05 19:45
Some more notes:
-  Although this issue is not present on that 6.0.x, we can't just downgrade to that due to https://github.com/osmdroid/osmdroid/issues/1209
-  I don't want to go all the way back to 5.6.5, because of the improvements that upgrading to 6.x brought.

Since pinch zooming works fine in the main map view, just not in LiveRide, I think we just need to figure it out.  The map view and overlays are configured entirely separately (it's a whole new `LiveRideActivity`, after all) so this could take some time to figure out.

**Comment by jezhiggins** [comment] 2020-05-05 21:28
Yes, my assumption at the moment is that one of the overlays that live ride uses is now getting in the way somehow. I have done a little bit of investigation an the gestures are getting down to the multitouch controller and the start of the pinch gesture is detected, but it's then being lost or interrupted. I'll experiment with the overlays, and see if any of them are trigger the problem.

**Comment by jezhiggins** [comment] 2020-05-05 21:35
Ok, found the cause - it's the lockOnLocation() call. 

I'll investigate a resolution in the morning.

**Comment by jezhiggins** [comment] 2020-05-05 22:47
OsmDroid's MyLocationNewOverlay now has its own support for locking on to the location and preventing the map from being panned around. However, it has exactly the same issue as my code in that it disables pinch-zoom. Sigh.

**Comment by jezhiggins** [comment] 2020-05-05 23:28
CycleStreets and OsmDroid lock-on location implementations are slightly different, but work essentially the same way. When locked, we're looking to intercept the MotionEvent.ACTION_MOVE event to prevent panning the map.
In OsmDroid's case, it then returns before the event can be processed by the multitouch controller. In CycleStreet's case we reenable location following and something in that code path - I think a map redraw again interferes with multitouch detection.
I have a fix which I need to double-check. If it's ok, we can apply it in CycleStreets and also submit as a PR to OsmDroid.

**Comment by jezhiggins** [comment] 2020-05-06 15:13
Raised issue on OsmDroid https://github.com/osmdroid/osmdroid/issues/1578

**Comment by mvl22** [comment] 2020-05-06 15:41
Nice work - thanks. Hopefully this can be fixed by them upstream.

**Closed** 2020-05-06 16:00 UTC
Labels: Bug - regression
